# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Unit-Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:

  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.3'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test $(go list ./... | grep -v /test/) -coverprofile coverage.out

    - name: Print Coverage
      run: go tool cover -func coverage.out
    
